#!/usr/bin/perl

use strict;
use warnings;
use IO::Socket::INET;
use Getopt::Long;

my $port = 80;
my $wait = 0;
my $help = 0;

my $result = GetOptions(
	"port=i" => \$port,
	"wait=i" => \$wait,
	"help"   => \$help,
);
usage() if (!$result || $help);

server($port, $wait);

# listen server
sub server {
	my ($port, $wait) = @_;

	my $sock = IO::Socket::INET->new(
		LocalAddr => "0:$port",
		Listen    => 5,
		ReuseAddr => 1,
	) || die $!;

	my $client = $sock->accept;

	sleep $wait if $wait;

	# read request
	while (<$client>) {
		# send response
		print $client $_;
	}
}

sub usage {
	die <<"END";
Usage: $0 [OPTION] FILE [FILE...]

  -p PORT      listen port (default 80)
  -w N         wait N seconds before send response
END
}
