ALL:
	$(MAKE) -C http_protocol_module_base_test
	$(MAKE) -C http_utility_test
	$(MAKE) -C module_base_test
	$(MAKE) -C protocol_module_base_test
	$(MAKE) -C protocol_module_ip_test
	$(MAKE) -C protocol_module_sessionless_test
	$(MAKE) -C protocol_module_sslid_test
	$(MAKE) -C ssl_protocol_module_base_test

clean:
	$(MAKE) -C http_protocol_module_base_test clean
	$(MAKE) -C http_utility_test clean
	$(MAKE) -C module_base_test clean
	$(MAKE) -C protocol_module_base_test clean
	$(MAKE) -C protocol_module_ip_test clean
	$(MAKE) -C protocol_module_sessionless_test clean
	$(MAKE) -C protocol_module_sslid_test clean
	$(MAKE) -C ssl_protocol_module_base_test clean
