ALL:
	$(MAKE) -C session_result_message
	$(MAKE) -C tcp_data_test
	$(MAKE) -C tcp_realserver_connect_socket_list
	$(MAKE) -C tcp_session
	$(MAKE) -C tcp_socket
	$(MAKE) -C tcp_ssl_socket
	$(MAKE) -C tcp_thread_message
	$(MAKE) -C udp_data_test

clean:
	$(MAKE) -C session_result_message clean
	$(MAKE) -C tcp_data_test clean
	$(MAKE) -C tcp_realserver_connect_socket_list clean
	$(MAKE) -C tcp_session clean
	$(MAKE) -C tcp_socket clean
	$(MAKE) -C tcp_ssl_socket clean
	$(MAKE) -C tcp_thread_message clean
	$(MAKE) -C udp_data_test clean
