ALL:
	$(MAKE) -f Makefile_logger_impl
	$(MAKE) -f Makefile_logger_ma_ac
	$(MAKE) -f Makefile_logger_ut

clean:
	$(MAKE) -f Makefile_logger_impl clean
	$(MAKE) -f Makefile_logger_ma_ac clean
	$(MAKE) -f Makefile_logger_ut clean
