ALL:
	$(MAKE) -C command_receiver_test
	$(MAKE) -C command_session_test
	$(MAKE) -C command_thread_test
	$(MAKE) -C endpoint_test
	$(MAKE) -C l7vs_command_test
	$(MAKE) -C l7vs_logger
	$(MAKE) -C l7vsadm_test
	$(MAKE) -C l7vsd_test
	$(MAKE) -C logger_implement_access
	$(MAKE) -C module_controls_test
	$(MAKE) -C module_test
	$(MAKE) -C other
	$(MAKE) -C parameter_test
	$(MAKE) -C realserver_test
	$(MAKE) -C replication_test
	$(MAKE) -C schedule_module_test
	$(MAKE) -C session_test
#	$(MAKE) -C session_thread_control_test
	$(MAKE) -C virtualservice_element_test
	$(MAKE) -C virtualservice_test

clean:
	$(MAKE) -C command_receiver_test clean
	$(MAKE) -C command_session_test clean
	$(MAKE) -C command_thread_test clean
	$(MAKE) -C endpoint_test clean
	$(MAKE) -C l7vs_command_test clean
	$(MAKE) -C l7vs_logger clean
	$(MAKE) -C l7vsadm_test clean
	$(MAKE) -C l7vsd_test clean
	$(MAKE) -C logger_implement_access clean
	$(MAKE) -C module_controls_test clean
	$(MAKE) -C module_test clean
	$(MAKE) -C other clean
	$(MAKE) -C parameter_test clean
	$(MAKE) -C realserver_test clean
	$(MAKE) -C replication_test clean
	$(MAKE) -C schedule_module_test clean
	$(MAKE) -C session_test clean
#	$(MAKE) -C session_thread_control_test clean
	$(MAKE) -C virtualservice_element_test clean
	$(MAKE) -C virtualservice_test clean
