/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 *        : mib2c.create-dataset.conf,v 5.4 2004/02/02 19:06:53 rstory Exp $
 *        : mib2c.notify.conf,v 5.3 2004/04/15 12:29:19 dts12 Exp $
 */
#ifndef NETSNMP_BRIDGE_H
#define NETSNMP_BRIDGE_H

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <string.h>

#include "MessengerClient.h"
#include "store_mibdata.h"
#include "message.h"
#include "../logger/logger_enum.h"

#define REPEAT_SEC  3

/*
 * column number definitions for table um7VirtualServiceTable
 */
#define COLUMN_UM7VSINDEX                   1
#define COLUMN_UM7VSPROTOCOL                2
#define COLUMN_UM7VSIPADDRESS               3
#define COLUMN_UM7VSPORTNUMBER              4
#define COLUMN_UM7VSSCHEDULEMODULE          5
#define COLUMN_UM7VSPROTOCOLMODULE          6
#define COLUMN_UM7VSPROTOCOLMODULEOPTION    7
#define COLUMN_UM7VSRESCHEDULE              8
#define COLUMN_UM7VSSORRYIPADDRESS          9
#define COLUMN_UM7VSSORRYPORTNUMBER         10
#define COLUMN_UM7VSSORRYTHRESHOLD          11
#define COLUMN_UM7VSSORRYFORCEFLAG          12
#define COLUMN_UM7VSQOSTHRESHOLDUP          13
#define COLUMN_UM7VSQOSTHRESHOLDDOWN        14
#define COLUMN_UM7VSTHROUGHPUTUP            15
#define COLUMN_UM7VSTHROUGHPUTDOWN          16

/*
 * column number definitions for table um7RealServerTable
 */
#define COLUMN_UM7RSINDEX                   1
#define COLUMN_UM7RSVIRTUALSERVICEINDEX     2
#define COLUMN_UM7RSIPADDRESS               3
#define COLUMN_UM7RSPORTNUMBER              4
#define COLUMN_UM7RSFORWARDMODE             5
#define COLUMN_UM7RSWEIGHT                  6
#define COLUMN_UM7RSACTIVECONN              7
#define COLUMN_UM7RSINACTIVECONN            8

/*
 * function declarations
 */
void    init_netsnmp_bridge(void *);
void    initialize_table_um7VirtualServiceTable();
void    initialize_table_um7RealServerTable();
void    getL7vsdData(unsigned int, void *);
int     send_um7StateAlert_trap();
int     send_um7VirtualServiceAlert_trap();
int     send_um7ReplicationAlert_trap();
int     send_um7LogLevelAlert_trap();
int     send_um7QoSAlarmOn_trap();
int     send_um7QoSAlarmOff_trap();
int     send_um7MessageAlert_trap();
Netsnmp_Node_Handler handle_um7LogVsdNetwork;
Netsnmp_Node_Handler handle_um7LogVsdNetworkBandwidth;
Netsnmp_Node_Handler handle_um7LogVsdNetworkNumConnection;
Netsnmp_Node_Handler handle_um7LogVsdNetworkQoS;
Netsnmp_Node_Handler handle_um7LogVsdVirtualService;
Netsnmp_Node_Handler handle_um7LogVsdRealServer;
Netsnmp_Node_Handler handle_um7LogVsdRealServerBalancing;
Netsnmp_Node_Handler handle_um7LogVsdSorryServer;
Netsnmp_Node_Handler handle_um7LogVsdReplication;
Netsnmp_Node_Handler handle_um7LogVsdStartStop;
Netsnmp_Node_Handler handle_um7LogVsdSystem;
Netsnmp_Node_Handler handle_um7LogVsdSystemMemory;
Netsnmp_Node_Handler handle_um7LogVsdSystemSocket;
Netsnmp_Node_Handler handle_um7LogVsdSystemSignal;
Netsnmp_Node_Handler handle_um7LogVsdEnvironment;
Netsnmp_Node_Handler handle_um7LogVsdEnvironmentParameter;
Netsnmp_Node_Handler handle_um7LogVsdLogger;
Netsnmp_Node_Handler handle_um7LogVsdParameter;
Netsnmp_Node_Handler handle_um7LogVsdEvent;
Netsnmp_Node_Handler handle_um7LogVsdSchedule;
Netsnmp_Node_Handler handle_um7LogVsdProgram;
Netsnmp_Node_Handler handle_um7LogVsdProtocol;
Netsnmp_Node_Handler handle_um7LogVsdModule;
Netsnmp_Node_Handler handle_um7LogVsadmParse;
Netsnmp_Node_Handler handle_um7LogVsadmOperate;
Netsnmp_Node_Handler handle_um7LogVsadmCommunicate;
Netsnmp_Node_Handler handle_um7LogVsadmConfigResult;
Netsnmp_Node_Handler handle_um7LogVsadmCommon;
Netsnmp_Node_Handler handle_um7LogVsadmLogger;
Netsnmp_Node_Handler handle_um7LogVsadmParameter;
Netsnmp_Node_Handler handle_um7LogVsadmProtocol;
Netsnmp_Node_Handler handle_um7LogVsadmModule;
Netsnmp_Node_Handler handle_um7LogSnmpStartStop;
Netsnmp_Node_Handler handle_um7LogSnmpManagerReceive;
Netsnmp_Node_Handler handle_um7LogSnmpManagerSend;
Netsnmp_Node_Handler handle_um7LogSnmpL7vsdReceive;
Netsnmp_Node_Handler handle_um7LogSnmpL7vsdSend;
Netsnmp_Node_Handler handle_um7LogSnmpLogger;
Netsnmp_Node_Handler handle_um7LogSnmpParameter;
Netsnmp_Node_Handler handle_um7StatMessage;
Netsnmp_Node_Handler handle_um7StatSnmpAgent;
Netsnmp_Node_Handler handle_um7StatReplication;
Netsnmp_Node_Handler um7VirtualServiceTable_handler;
Netsnmp_Node_Handler um7RealServerTable_handler;

#endif                          /* NETSNMP_BRIDGE_H */
