/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf,v 5.3 2004/04/15 12:29:19 dts12 Exp $
 */
#ifndef ULTRAMONKEYL7_H
#define ULTRAMONKEYL7_H

/*
 * function declarations
 */
int             send_l7vsError_trap(void);

#endif                          /* ULTRAMONKEYL7_H */
